<?php

namespace Container9lWvPUJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Impl\CommandeService' shared autowired service.
     *
     * @return \App\Service\Impl\CommandeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommandeServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'CommandeService.php';

        return $container->privates['App\\Service\\Impl\\CommandeService'] = new \App\Service\Impl\CommandeService(($container->privates['App\\Repository\\CommandeRepository'] ?? $container->load('getCommandeRepositoryService')), ($container->privates['App\\Repository\\PaiementRepository'] ?? $container->load('getPaiementRepositoryService')));
    }
}
