<?php

namespace Container9lWvPUJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComplementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ComplementController' shared autowired service.
     *
     * @return \App\Controller\ComplementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ComplementController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ComplementServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'ComplementService.php';

        $container->services['App\\Controller\\ComplementController'] = $instance = new \App\Controller\ComplementController(new \App\Service\Impl\ComplementService(($container->privates['App\\Repository\\ComplementRepository'] ?? $container->load('getComplementRepositoryService')), ($container->privates['App\\Service\\Impl\\ImageStorageService'] ?? $container->load('getImageStorageServiceService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ComplementController', $container));

        return $instance;
    }
}
