<?php

namespace ContainerAbzG8hF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageStorageServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Impl\ImageStorageService' shared autowired service.
     *
     * @return \App\Service\Impl\ImageStorageService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ImageStorageServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'ImageStorageService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cloudinary'.\DIRECTORY_SEPARATOR.'cloudinary_php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Cloudinary.php';

        return $container->privates['App\\Service\\Impl\\ImageStorageService'] = new \App\Service\Impl\ImageStorageService(new \Cloudinary\Cloudinary(['cloud' => ['cloud_name' => $container->getEnv('CLOUDINARY_CLOUD_NAME'), 'api_key' => $container->getEnv('CLOUDINARY_API_KEY'), 'api_secret' => $container->getEnv('CLOUDINARY_API_SECRET')], 'url' => ['secure' => true]]));
    }
}
