parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Cloudinary\Cloudinary:
    arguments:
      $config:
        cloud:
          cloud_name: '%env(CLOUDINARY_CLOUD_NAME)%'
        api:
          api_key: '%env(CLOUDINARY_API_KEY)%'
          api_secret: '%env(CLOUDINARY_API_SECRET)%'
        url:
          secure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'


  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
  App\Service\MenuServiceInterface: '@App\Service\Impl\MenuService'
  App\Service\ImageStorageServiceInterface: '@App\Service\Impl\ImageStorageService'
  App\Service\MenuPriceServiceInterface: '@App\Service\Impl\MenuPriceService'