<?php

namespace ContainerUWbxleU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeExtension_CsrfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type_extension.csrf' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'Csrf'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'FormTypeCsrfExtension.php';

        return $container->privates['form.type_extension.csrf'] = new \Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension(($container->privates['security.csrf.same_origin_token_manager'] ?? self::getSecurity_Csrf_SameOriginTokenManagerService($container)), true, '_token', ($container->services['translator'] ?? self::getTranslatorService($container)), 'validators', ($container->privates['form.server_params'] ?? $container->load('getForm_ServerParamsService')), $container->parameters['form.type_extension.csrf.field_attr'], ['App\\Form\\Catalogue\\BurgerCreateFormType' => 'submit', 'App\\Form\\Catalogue\\BurgerFilterFormType' => 'submit', 'App\\Form\\Catalogue\\BurgerUpdateFormType' => 'submit', 'App\\Form\\Catalogue\\ComplementFilterFormType' => 'submit', 'App\\Form\\Catalogue\\ComplementUpsertFormType' => 'submit', 'App\\Form\\Catalogue\\MenuCreateFormType' => 'submit', 'App\\Form\\Catalogue\\MenuFilterFormType' => 'submit', 'App\\Form\\Catalogue\\MenuUpdateFormType' => 'submit', 'App\\Form\\Client\\ClientCommandeFilterFormType' => 'submit', 'App\\Form\\Client\\ClientFilterFormType' => 'submit', 'App\\Form\\Commande\\CommandeListFilterFormType' => 'submit', 'App\\Form\\Livraison\\AssignLivreurFormType' => 'submit', 'App\\Form\\Livraison\\LivraisonFilterFormType' => 'submit']);
    }
}
