<?php

namespace ContainerUWbxleU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MenuController' shared autowired service.
     *
     * @return \App\Controller\MenuController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MenuController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MenuServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'MenuService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MenuPriceServiceInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Impl'.\DIRECTORY_SEPARATOR.'MenuPriceService.php';

        $a = ($container->privates['App\\Repository\\BurgerRepository'] ?? $container->load('getBurgerRepositoryService'));
        $b = ($container->privates['App\\Repository\\ComplementRepository'] ?? $container->load('getComplementRepositoryService'));

        $container->services['App\\Controller\\MenuController'] = $instance = new \App\Controller\MenuController(new \App\Service\Impl\MenuService(($container->privates['App\\Repository\\MenuRepository'] ?? $container->load('getMenuRepositoryService')), $a, $b, ($container->privates['App\\Service\\Impl\\ImageStorageService'] ?? $container->load('getImageStorageServiceService')), new \App\Service\Impl\MenuPriceService($a, $b)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\MenuController', $container));

        return $instance;
    }
}
