<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUWbxleU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUWbxleU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUWbxleU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUWbxleU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUWbxleU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UWbxleU',
    'container.build_id' => 'e545f5e4',
    'container.build_time' => 1768428276,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUWbxleU');
