<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAbzG8hF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAbzG8hF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAbzG8hF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAbzG8hF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAbzG8hF\App_KernelDevDebugContainer([
    'container.build_hash' => 'AbzG8hF',
    'container.build_id' => 'c0a61461',
    'container.build_time' => 1767041137,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAbzG8hF');
